apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.frontend.rule: "PathPrefixStrip:/influxdb"
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      nodePort: 30080
  externalIPs:
    - 192.168.1.102