# This is a basic workflow to help you get started with Actions

name: Deploy InfluxDB to Minikube

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run:  echo $(hostname)

      - name: Check Minikube
        run: wget "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        run: sudo cp minikube-linux-amd64 /usr/local/bin/minikube
        run: sudo chmod 755 /usr/local/bin/minikube

      - name: Check Minikube state
        run: minikube start --driver=docker
        run: minikube status
        run: docker version

      # Runs a set of commands using the runners shell
      - name: Deploy InfluxDB
        run: |
            kubectl apply -f /home/master/k8s_uoc/influxdb/influxdb-deploy.yaml
            kubectl apply -f /home/master/k8s_uoc/influxdb/influxdb-pvc.yaml
            kubectl apply -f /home/master/k8s_uoc/influxdb/influxdb-service.yaml
